### ISSUE TITLE
E: Unable to locate package python-serial

### ISSUE THREAD

**Issue by andrislapins** [edi-riga/MansOS#2] opened 2021-02-16 09:16 UTC
Could not download python-serial package with apt on Ubuntu 20.04.
Temporary solution: comment out "pyhton-serial" on last line in mos/make/Makefile file.

**Comment by DRG996** [comment] 2021-02-16 09:30
also work when replace "pyhton-serial" to "pyhton3-serial"

**Comment by jjanis** [comment] 2021-02-16 09:32
Duplicate of #1

**Closed as completed by jjanis** 2021-02-16 09:32 UTC

**Comment by erbanku** [comment] 2022-03-30 13:45
`sudo apt install python3-serial` works

**Comment by EngineerHamziey** [comment] 2023-11-24 09:41
thanks so much @sungminlee114, I really appreciate.
using python3-serial worked just like you said, I have spent hours on this before seeing this post. thanks once again.
here is the command I used, in case anyone else needed it, "sudo apt -y install python3-serial"

**Comment by Nadeem-Ullah** [comment] 2024-01-20 14:09
"sudo apt-get install python3-serial" and "sudo apt-y install python3-serial" both of them worked for me and it said that:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-serial is already the newest version (3.4-5.1).
> 0 upgraded, 0 newly installed, 0 to remove and 136 not upgraded.

But after that when I enter the following command:
"miniterm /dev/ttyUSB5 -e"
it gives me an error that:

> ould not open port '/dev/ttyUSB5': [Errno 2] could not open port /dev/ttyUSB5: [Errno 2] No such file or directory: '/dev/ttyUSB5

Any help will be appreciated
